"""messages table

Revision ID: 87e92c87d5e5
Revises: 0001
Create Date: 2026-09-17 11:37:18.052102

"""
from alembic import op
import sqlalchemy as sa


revision = '87e92c87d5e5'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_ticket_created', 'messages', ['ticket_id', 'created_at'], unique=False)
    # Note: ix_tickets_agent_id / ix_tickets_customer_id already exist in the database from
    # migration 0001; the model now declares them so autogenerate no longer wants to drop them.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_messages_ticket_created', table_name='messages')
    op.drop_table('messages')
