"""ticket read states

Revision ID: f679192f699c
Revises: 87e92c87d5e5
Create Date: 2026-09-17 12:42:06.351661

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'f679192f699c'
down_revision = '87e92c87d5e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_read_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'user_id', name='uq_read_state_ticket_user')
    )
    op.create_index(op.f('ix_ticket_read_states_ticket_id'), 'ticket_read_states', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_read_states_ticket_id'), table_name='ticket_read_states')
    op.drop_table('ticket_read_states')
    # ### end Alembic commands ###
